In [1]:
import pandas as pd

In [2]:
dataset= pd.read_csv("PrePlacement.csv")
dataset

,sl_no,gender,ssc_p,ssc_b,hsc_p,hsc_b,hsc_s,degree_p,degree_t,workex,etest_p,specialisation,mba_p,status,salary
0,1,M,67.00,Others,91.00,Others,Commerce,58.00,Sci&Tech,No,55.0,Mkt&HR,58.80,Placed,270000.0
1,2,M,79.33,Central,78.33,Others,Science,77.48,Sci&Tech,Yes,86.5,Mkt&Fin,66.28,Placed,200000.0
2,3,M,65.00,Central,68.00,Central,Arts,64.00,Comm&Mgmt,No,75.0,Mkt&Fin,57.80,Placed,250000.0
3,4,M,56.00,Central,52.00,Central,Science,52.00,Sci&Tech,No,66.0,Mkt&HR,59.43,Not Placed,0.0
4,5,M,85.80,Central,73.60,Central,Commerce,73.30,Comm&Mgmt,No,96.8,Mkt&Fin,55.50,Placed,425000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211,M,80.60,Others,82.00,Others,Commerce,77.60,Comm&Mgmt,No,91.0,Mkt&Fin,74.49,Placed,400000.0
211,212,M,58.00,Others,60.00,Others,Science,72.00,Sci&Tech,No,74.0,Mkt&Fin,53.62,Placed,275000.0
212,213,M,67.00,Others,67.00,Others,Commerce,73.00,Comm&Mgmt,Yes,59.0,Mkt&Fin,69.72,Placed,295000.0
213,214,F,74.00,Others,66.00,Others,Commerce,58.00,Comm&Mgmt,No,70.0,Mkt&HR,60.23,Placed,204000.0
214,215,M,62.00,Central,58.00,Others,Science,53.00,Comm&Mgmt,No,89.0,Mkt&HR,60.22,Not Placed,0.0

In [3]:
dataset.isnull().sum()

sl_no             0
gender            0
ssc_p             0
ssc_b             0
hsc_p             0
hsc_b             0
hsc_s             0
degree_p          0
degree_t          0
workex            0
etest_p           0
specialisation    0
mba_p             0
status            0
salary            0
dtype: int64

In [4]:
dataset.select_dtypes(include='number').cov()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
sl_no,3870.000000,-52.641355,-58.106028,-40.413645,52.556168,8.102336,2.449065e+04
ssc_p,-52.641355,117.228377,60.348373,42.897137,37.659225,24.535952,9.017549e+05
hsc_p,-58.106028,60.348373,118.755706,34.819820,35.461678,22.555846,7.633598e+05
degree_p,-40.413645,42.897137,34.819820,54.151103,21.929469,17.272020,4.651315e+05
etest_p,52.556168,37.659225,35.461678,21.929469,176.251018,16.886973,3.842344e+05
mba_p,8.102336,24.535952,22.555846,17.272020,16.886973,34.028376,1.262455e+05
salary,24490.654206,901754.893936,763359.777657,465131.504238,384234.419257,126245.485547,2.395714e+10

In [ ]:
#Covariance explanation between degree and etest & etest and Mba 
degree_p & etest_p covariance is 21.929469. Its a positive covariance. If student performance well in degree, he/she can perform well in etest.
etest_p & mba_p covariance is 16.886973. Its a positive covariance. If student performance well in etest, he/she can perform well in mba.

In [5]:
dataset.select_dtypes(include='number').corr()

             sl_no     ssc_p     hsc_p  degree_p   etest_p     mba_p    salary
sl_no     1.000000 -0.078155 -0.085711 -0.088281  0.063636  0.022327  0.002543
ssc_p    -0.078155  1.000000  0.511472  0.538404  0.261993  0.388478  0.538090
hsc_p    -0.085711  0.511472  1.000000  0.434206  0.245113  0.354823  0.452569
degree_p -0.088281  0.538404  0.434206  1.000000  0.224470  0.402364  0.408371
etest_p   0.063636  0.261993  0.245113  0.224470  1.000000  0.218055  0.186988
mba_p     0.022327  0.388478  0.354823  0.402364  0.218055  1.000000  0.139823
salary    0.002543  0.538090  0.452569  0.408371  0.186988  0.139823  1.000000

In [6]:
#Correlation explanation between degree and etest & etest and Mba 
mba_p & salary_p correlation is 0.139823. Its a positive covariance. but it only 13% percentange of positive correlation.
If student mba percentage increase, salary also get increase.

SyntaxError: invalid syntax (1677390784.py, line 2)